Repository kowainik/cake-slayer, pull requests merged in 2019-09, with the labels that each got.

#2 Polish initial scaffolding
  .travis.yml
  cake-slayer.cabal
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack.yaml
  test/Prelude.hs
Labels: CI

#13 [#4] Implement errors function
  cake-slayer.cabal
  src/CakeSlayer.hs
  src/CakeSlayer/Error.hs
Labels: enhancement

#12 [#3] Implement `Has` typeclass
  cake-slayer.cabal
  src/CakeSlayer.hs
  src/CakeSlayer/Has.hs
Labels: enhancement

#15 [#5] Implement application monad
  cake-slayer.cabal
  src/CakeSlayer.hs
  src/CakeSlayer/Monad.hs
Labels: enhancement

#17 [#6] Write passwords module
  .travis.yml
  cake-slayer.cabal
  src/CakeSlayer/Password.hs
  src/CakeSlayer/Random.hs
  stack.yaml
  test/Spec.hs
  test/Test/Password.hs
Labels: enhancement, tests

#18 [#7] Implement `MonadJwt` effect
  cake-slayer.cabal
  src/CakeSlayer/Jwt.hs
  stack.yaml
  test/Spec.hs
  test/Test/Gen.hs
  test/Test/Jwt.hs
  test/Test/Password.hs
Labels: enhancement

#22 [#9] Implement DB functions
  cake-slayer.cabal
  src/CakeSlayer.hs
  src/CakeSlayer/Db.hs
  src/CakeSlayer/Error.hs
  stack.yaml
Labels: enhancement

#24 [#8] Implement `MonadMeasured` effect
  cake-slayer.cabal
  src/CakeSlayer/Measure.hs
Labels: enhancement

#27 [#20] Bring time module
  cake-slayer.cabal
  src/CakeSlayer/Jwt.hs
  src/CakeSlayer/Time.hs
Labels: enhancement

#28 [#21] Patch 'MonadJwt' to handle different payloads
  cake-slayer.cabal
  src/CakeSlayer/Jwt.hs
  test/Spec.hs
  test/Test/Jwt.hs
  test/Test/Mock.hs
Labels: enhancement

#30 Add executeNamed_ function
  src/CakeSlayer/Db.hs
Labels: enhancement

#31 [#25] Refactor `timedActionImpl` to allow to specify which metrics to use
  src/CakeSlayer/Measure.hs
Labels: enhancement

#32 [#19] Experiment with mixins for Prelude module
  cake-slayer.cabal
  src/Prelude.hs
  test/Prelude.hs
Labels: enhancement

#34 [#26] Swagger-helper functions
  cake-slayer.cabal
  src/CakeSlayer/Swagger.hs
Labels: enhancement
